### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by madaidan** [juga0/dhcpcanon#32]
There hasn't been a commit since 2018 and https://github.com/juga0/dhcpcanon#current-status says:

> WIP, still not recommended for end users.

Does that mean this project is dead? Are there any security issues? Should it still be used?

**Comment by juga0** [comment]
Hi @madaidan, thanks for your comments.

> There hasn't been a commit since 2018 and https://github.com/juga0/dhcpcanon#current-status says:
> 
> > WIP, still not recommended for end users.

To use/start `dhcpcanon`  you need to use the command line, what in general end users should not need to know.
The main reason to say that is not recommended for end users, is that it was not well integrated with a system network manager, as Gnome NetworkManager, so that users do not need to use the command line.
> 
> Does that mean this project is dead? 

I still intend to continue with it, but unfortunately i did not have time so far.

> Are there any security issues? 

No that i know of.

> Should it still be used?

As the status you pointed out mention: "Testers welcomed."
If you're a technical person, it would be great if you test it and report back.
If you'd like to use it in your main/daily system, it might give you some problem.

Hope this answer your questions.

**Comment by madaidan** [comment]
Thanks for the response! It answered everything.
